### ISSUE TITLE
How to check if SelectablePickMesh is selected?

### ISSUE THREAD

**Issue by guimcaballero** [aevyrie/bevy_mod_picking#10]
I was playing around with this crate (pretty cool btw!). I'm trying to make the wasd keys move the current selected entity. My approach has been to make a system with `mut query: Query<&mut SelectablePickMesh>`, and then iterate over the query and check for `selected`, but it turns out it's a private field and it can't be accessed.

Is there another way of doing what I'm trying to do? Or should `selected` be marked as public?

**Comment by aevyrie** [comment]
Good call, yeah, I didn't put much thought into exposing the pick information.

> My approach has been to make a system with mut query: Query<&mut SelectablePickMesh>, and then iterate over the query and check for selected, but it turns out it's a private field and it can't be accessed.

That sounds like the right approach to me! I'll add a public getter function.

**Comment by aevyrie** [comment]
@guimcaballero Let me know if this change works for you!

**Comment by guimcaballero** [comment]
Yup! Works great, thanks for the fast change!

Here's what I'm working on:

![bavy](https://user-images.githubusercontent.com/29580620/92281801-b25f9800-eefc-11ea-9828-c46486e8bd28.gif)

It's an early prototype for an RTS style game, but it's more experimentation than anything else. You can move the camera if  nothing is selected, you can move an entity if it's selected, and that's basically it haha.

**Comment by aevyrie** [comment]
@guimcaballero That is super cool! You should post that in the bevy discord showcase channel!
