### ISSUE TITLE
issue with creating hierarchial structures and the picking mod

### ISSUE THREAD

**Issue by rezural** [aevyrie/bevy_mod_picking#100]
I have a strange bug with adding children to a parent entity, despawning them, then adding them in again:

https://github.com/rezural/bevy_mod_picking/commits/3d-scene-heirarchy-bug 
the example is in this branch

commit 644e10cf76ad817082ac2539ef14614923f7d96a works as expected
whereas commit 14df054b03e8e7125215f98b3801153219466623 creates 2 sets of children, one offset a little.

Reproduce:

git checkout 644e10cf76ad817082ac2539ef14614923f7d96a
cargo run --release --example 3d_scene_heirarchy

git checkout 14df054b03e8e7125215f98b3801153219466623
cargo run --release --example 3d_scene_heirarchy

**Comment by aevyrie** [comment]
Did you try asking in the Bevy discord #help channel? They might be able to help root-cause this a bit quicker than I am able to in my limited time. 🙂

**Comment by aevyrie** [comment]
Unless you have a picking-related issue with this, I'm going to close this. :)
