### ISSUE TITLE
how to assign dynamic hover color depending?

### ISSUE THREAD

**Issue by sderrico** [aevyrie/bevy_mod_picking#103]
Hello,

Thank you for this excellent feature!

Curiosity, the mesh in our scene are categorized in two camps: friends and enemies.

What would be the best strategy to dynamically assign red or green hover color depending of the mesh camp?
- is there a way to set it when the mesh is spawn?
- is it better to assign it when the user pass the cursor over the mesh?
- other way?

Thank you!
Sébastien

**Comment by aevyrie** [comment]
The built in system only allows you to set a global hover/select color.

I'd recommend creating a system that queries entities and sets their color based on their hover state, as well as if it's a friend or enemy. You could start with the mesh highlighting system: https://github.com/aevyrie/bevy_mod_picking/blob/f33a15251fed0f0899762d649ffae420b8804b82/src/highlight.rs#L42

**Comment by sderrico** [comment]
Cool! Thank you very much @aevyrie !

**Comment by gilescope** [comment]
How does one set the global hover/select color?

**Comment by aevyrie** [comment]
You can update the `Handle<StandardMaterial>`s in the `MeshButtonMaterials` resource with your own materials. See how `global_button_materials` is accessed here:

https://github.com/aevyrie/bevy_mod_picking/blob/1b1278b289c459e5373a301666ccd138a3a4bc3d/src/highlight.rs#L67-L69
