### ISSUE TITLE
Does not work with bevy main's require component

### ISSUE THREAD

**Issue by Sheepyhead** [aevyrie/bevy_mod_picking#105]
So I was having issues with using this repo with bevy main, and I stumbled into an issue with queries like Query<&PickingCamera> and it led me to realize that while Component derives have been added to components on this repo and on bevy_mod_raycast, there has not been a release of raycast with this update, and thus when this repo pulls bevy_mod_raycast v0.2 you get components that do not derive Component.

The ideal solution would be to make a new release for bevy_mod_raycast, then bump the version number on this repo.

**Comment by aevyrie** [comment]
Hey @Sheepyhead, you might need to delete your cargo lock - the cargo.toml in this repo pulls from the git/master branch of mod_raycast. I generally try to track bevy/main on my master branches of both repos, and depend on the cargo versions when I make releases to match Bevy's.

**Comment by Sheepyhead** [comment]
I have deleted both target and Cargo.lock and I was still having dependency issues, seems like it might be an issue with different bevy versions between my project and what's in the cargo.toml of this repo - either way it makes it unusable with bevy main in an external project without cloning this repo and changing the dependencies manually, if you try to take a Query<&PickingCamera> for instance.

**Comment by aevyrie** [comment]
> either way it makes it unusable with bevy main in an external project without cloning this repo and changing the dependencies manually

Not sure what you mean. I can make a sample project that depends on Bevy/main, as well as mod_picking/master (which depends on Bevy/main) without any issues out of the box. What does your mod_picking dependency look like in your cargo.toml?

**Comment by aevyrie** [comment]
I created a sample project to demonstrate that this is working: https://github.com/aevyrie/picking_test
Also see the cargo.toml: https://github.com/aevyrie/picking_test/blob/main/Cargo.toml

**Comment by aevyrie** [comment]
> Here's a minimal example that fails to compile https://github.com/Sheepyhead/bevy_test/tree/bevy_mod_picking_105 

Thanks, I'll try it out

**Comment by aevyrie** [comment]
I did a diff, and it looks like your cargo.lock is pointing to an old bevy commit before the component derive was added: https://github.com/bevyengine/bevy/commit/b91541b6efff2236f6aefca0f2baa09aba54f505
