### ISSUE TITLE
Is it possible to us `bevy_mod_picking` only for a specified State?

### ISSUE THREAD

**Issue by chtotut** [aevyrie/bevy_mod_picking#107]
Work:
```rust
impl Plugin for Battle {
    fn build(&self, app: &mut App) {
        app.add_plugin(DefaultPickingPlugins)
            .add_startup_system(setup.system());
    }
}
```

Doesn't work:
```rust
impl Plugin for Battle {
    fn build(&self, app: &mut App) {
        app.add_plugin(DefaultPickingPlugins)
            .add_system_set(SystemSet::on_enter(GameState::Battle).with_system(setup.system()));
    }
}
```

(system `setup` creates entities and set up `PickableBundle::default()`)

The `bevy_mod_picking` doesn't work then state is `GameState::Battle`.

**Comment by aevyrie** [comment]
Yes. The plugin uses run criteria to handle enabling and disabling. What you can do is `.on_enter` run a system that will enable picking in the `PickingPluginsState` resource.
