### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by intendednull** [aevyrie/bevy_mod_picking#109]
Experiencing a memory leak on all web browsers (master branch). Removing the `PickableBundle` from my component fixes the issue. Any ideas or suggestions for debugging this?

**Comment by aevyrie** [comment]
Do you see this when disabling the plugin outright? How severe is the leak?

**Comment by intendednull** [comment]
@aevyrie yes, disabling the plugin also fixes the issue. The leak causes the browser to crash after a minute or so.

**Comment by aevyrie** [comment]
I spent some time looking into this but was unable to replicate. On the Bevy discord, I saw some other discussions about OOM on wasm. I'll close this for now, but we can always reopen if we find any evidence that this is caused by this plugin.
