### ISSUE TITLE
`BoundVol` causes app to hang indefinitely

### ISSUE THREAD

**Issue by intendednull** [aevyrie/bevy_mod_picking#110]
Adding `BoundVol` to my components causes my app to freeze on startup (showing only a blank white screen). Seems like it's caught in an infinite loop somewhere? On web (not sure that matters).

I am generated meshes by hand, which seems to be the culprit. They render do correctly, but aren't playing well with `BoundVol`. Replacing all my meshes with generic `Cube`s seems to work just fine. [Here's my relevant code](https://gist.github.com/intendednull/40cd183ec0808da8e405a40037760434)

**Comment by aevyrie** [comment]
I'm fairly certain there isn't an infinite loop or recursion in the bounding volume calculation. Are you running this in release mode? the naive bounding volume generation can take a while in debug. Can you try limiting the number of vertices in your generated meshes to a very small number to verify?

**Comment by intendednull** [comment]
@aevyrie appreciate the quick response! Yes it's optimized, and I've left it running for a few minutes with no resolve. Reducing the number of vertices doesn't appear to have any effect.

**Comment by aevyrie** [comment]
Interesting, would you mind putting together a minimal example I could use to debug?

**Comment by intendednull** [comment]
Can do, though I am low on time at the moment, will rip it out of my project when possible.

**Comment by aevyrie** [comment]
Bound vols removed in favor of built-in AABBs. Resolving this.
