### ISSUE TITLE
How to get the World coordinates vector of where the ray hits the picked object?

### ISSUE THREAD

**Issue by Calamari** [aevyrie/bevy_mod_picking#112]
The goal I am trying to wrap my head around is this:
Suppose I have selected a unit then I want to click somewhere on the world/map so the unit can have a new destination to go to.

How would I go about it? As far as I can see, the events coming out of the system don't have the intersection vector, where the ray hit the world. How could I go about achieving this?

**Comment by aevyrie** [comment]
> How would I go about it? As far as I can see, the events coming out of the system don't have the intersection vector, where the ray hit the world. How could I go about achieving this?

The first thing to note is that this library is mostly meant for simple picking use, where you just want to know what you've clicked/hovered. However, it is built on top of [bevy_mod_raycast](https://github.com/aevyrie/bevy_mod_raycast), which does the actual raycasting intersection checks. You may be able to accomplish your goal without explicitly `use`ing `bevy_mod_raycast`, but I wanted to note this in case you end up running into types/functions that this library doesn't expose.

...

What is the "world" in this case? It sounds like what you want is to click on some "ground" mesh and use that intersection point as your unit's destination.

The simplest way to do this would be to add some ground mesh, make it pickable, then check where the intersection occurred by querying your `PickingCamera` and calling [`intersect_top`](https://docs.rs/bevy_mod_picking/latest/bevy_mod_picking/struct.RayCastSource.html#method.intersect_top), which will give you an [`Intersection`](https://docs.rs/bevy_mod_raycast/latest/bevy_mod_raycast/struct.Intersection.html) with the world coordinates you're after. Alternatively, you could forgo using any sort of ground mesh, and intersect a mathematical ground plane using [`intersect_primitive`](https://docs.rs/bevy_mod_picking/latest/bevy_mod_picking/struct.RayCastSource.html#method.intersect_primitive). This will be more performant, but won't allow you to have any change in elevation from the plane.
