### ISSUE TITLE
Update to support Bevy 0.6

### ISSUE THREAD

**Issue by mattbradbury** [aevyrie/bevy_mod_picking#114]
Just a tracking issue so I can follow when the new version gets released.

Is master being worked on it now?

**Comment by aevyrie** [comment]
Yup, I had to do some upstream work on mod_raycast first.

**Comment by jbcurtin** [comment]
I'm successfully using `bevy_mod_picking` master branch with bevy 0.6.

**Comment by mirkoRainer** [comment]
Just tracking this issue too.
Thank you for what you do.

**Comment by aevyrie** [comment]
0.5 is out!

**Comment by mirkoRainer** [comment]
🙌 🎊 🎉

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
