### ISSUE TITLE
Can you use bevy_mod_picking for UI elements?

### ISSUE THREAD

**Issue by pop** [aevyrie/bevy_mod_picking#119]
I'm curious if bevy_mod_picking *can* be used to select UI elements like buttons and if it can how would one implement that?

If that is not possible with bevy_mod_picking, would you be open to that feature being added?

I'm writing a bunch of code to basically do what bevy_mod_picking does but for my UI and I figured I should either document how to use bevy_mod_picking for this (and remove some bloated code) or try adding the feature upstream if you're open to it.

**Comment by aevyrie** [comment]
The `Selection`, `FocusPolicy`, and `Interaction` bits of mod_picking use bevy's types/components for this reason. It should be possible to compose 3d picking interaction with UI interaction somewhat seamlessly. 

> I'm writing a bunch of code to basically do what bevy_mod_picking does but for my UI 

What are you doing, more specifically? You should be able to use bevy's built in UI components.

**Comment by pop** [comment]
I don't have time to make this contribution and bevy's UI interface is good enough the more I use it.
