### ISSUE TITLE
PausedForBlockers get stuck in true state, if UI is removed while it is blocked

### ISSUE THREAD

**Issue by BessBrahmin** [aevyrie/bevy_mod_picking#124]
Hello, I ran to an issue with the picker not working on my own project. I tracked the issue into the method "pause_for_picking_blockers" setting pause.0 = true during the game being in the main menu. But when I went to game from the menu the pause would be stuck on true, since the for statement in the method. That should make it false never triggers due there being no UI elements outside of the Main menu.

I fixed this myself by moving the pause.0 = false to the end of the method and outside of the for statement, since the pause.0 = true calls return right after it anyway.

Since I'm not familiar with this package I don't want to make a pull request, since my fix might actually cause many issues I couldn't predict. So I made this ticket instead, maybe someone who is familiar with the code is able to make a proper fix for this issue.

**Comment by aevyrie** [comment]
@BessBrahmin please go ahead and make a PR, it will be easier to review if it has any unintended side effects. Thank you!

**Comment by docDock** [comment]
This happens to me as well. I will submit a pr that fixes this.
