### ISSUE TITLE
Bevy 0.7 breaks trait implementations

### ISSUE THREAD

**Issue by rask** [aevyrie/bevy_mod_picking#127]
When installing `0.5.4` on Bevy `0.7`, the trait implementations for `PluginGroup` and `Bundle` fail for the quickstart code as described in the README file.

Reverting to Bevy `0.6.*` makes the issue go away and the README quickstart works without a compiler error.

I don't know enough about Rust or Bevy to know why this happens or how to fix it.

**Comment by aevyrie** [comment]
This library just needs to be update for bevy 0.7 :)
