### ISSUE TITLE
bevy_mod_picking 0.5.4 breaks because bevy_mod_raycast = ">=0.3.9" is using bevy 0.7

### ISSUE THREAD

**Issue by lantoniogc** [aevyrie/bevy_mod_picking#128]
I found this when trying to recompile the dependencies in my project because it used bevy_mod_raycast `0.4.0` instead of `0.3.x`

**Comment by kanerogers** [comment]
I'm unfortunately having the same issue. 😦

**Comment by aevyrie** [comment]
Oof. Thanks for the heads up.

**Comment by aevyrie** [comment]
Published 0.5.5 that fixes this.
Published 0.6.1 to prevent this in future releases.
Thank you for the report!

**Comment by kanerogers** [comment]
> Published 0.5.5 that fixes this. Published 0.6.1 to prevent this in future releases. Thank you for the report!

Thanks for the quick turnaround! 😁
