### ISSUE TITLE
Supporting picking from Mesh2D (this enables support for Lyon users)

### ISSUE THREAD

**Issue by SUPERCILEX** [aevyrie/bevy_mod_picking#130]
See https://github.com/bevyengine/bevy/discussions/4598#discussioncomment-2636673

**Comment by aevyrie** [comment]
Implemented upstream here: https://github.com/aevyrie/bevy_mod_raycast/pull/38

I'll add a 2d example to mod_picking to wrap this up.

**Comment by paulrosania** [comment]
I think this is implemented now? Would you be open to cutting a release with this? I'm super excited to play with it!

**Comment by aevyrie** [comment]
Ah, yup. I need to work on porting an update for both mod_raycast and mod_picking. I'll close this as it's resolved in `main`.

**Comment by paulrosania** [comment]
Thanks! I got it to work with Bevy 0.7 with just a couple minor tweaks to
mod_raycast, if a PR would be helpful.

@ptr

**Comment by aevyrie** [comment]
Done. :slightly_smiling_face:

**Comment by paulrosania** [comment]
Amazing, thank you! ❤️
