### ISSUE TITLE
SelectionEvents do not work

### ISSUE THREAD

**Issue by Kulasko** [aevyrie/bevy_mod_picking#131]
I did try inserting the corresponding `Events` struct as a resource.

It seems that not only was that missing, there is also nothing writing those `SelectionEvent`s.
Perhaps that feature isn't implemented yet? I am confused because `SelectionEvent` is available going through crates.io and it even got some documentation. Do I need to add another Plugin, perhaps?

**Comment by aevyrie** [comment]
Have you tried running the `events` example? This should show you how to view all the event types: https://github.com/aevyrie/bevy_mod_picking/blob/main/examples/events.rs

**Comment by Kulasko** [comment]
I did run the example successfully. However, it only demonstrates `PickingEvent`s, not `SelectionEvent`s.
I can implement the system sending `SelectionEvent`s manually, but I was just wondering if them not being generated was intended behaviour or if I did something wrong in my configuration.

**Comment by aevyrie** [comment]
I'm not sure I understand what you're doing, can you share some example code?

> I did run the example successfully. However, it only demonstrates `PickingEvent`s, not `SelectionEvent`s.

`SelectionEvents` are a type of `PickingEvent`, see here: https://github.com/aevyrie/bevy_mod_picking/blob/34f2f64d7e8f985d09fc71c7e4791579d72b5f23/src/events.rs#L21

**Comment by Kulasko** [comment]
> `SelectionEvent`s are a type of `PickingEvent`

That was the missing puzzle piece, thanks a lot!
I did not see it was used inside `PickingEvent`, so I was under the impression that it is an individual event signaling any change of `Selection` components.

That was an error on my side, so I am sorry I did waste your time and I hope you didn't mind too much.
