### ISSUE TITLE
work with egui

### ISSUE THREAD

**Issue by YoshieraHuang** [aevyrie/bevy_mod_picking#134]
Now i want to do mouse selection with this mod and bevy_egui. When i clicked the egui window, the entity is deselected. I know the `NoDeselect` component is designed to solve this, but the egui windows dont exist in the ecs world. Is there any workaround?

**Comment by YoshieraHuang** [comment]
An idea comes out: An invisible plane with `PickableBundle` and `NoDeselect` component, which has same translation and size as the egui window and located just behind the window.

**Comment by aevyrie** [comment]
We use mod_picking with egui by disabling this plugin when egui [wants pointer input](https://docs.rs/egui/latest/egui/struct.Context.html#method.wants_pointer_input)

**Comment by YoshieraHuang** [comment]
Thank you for the solution.
