### ISSUE TITLE
Relicense bevy_mod_picking under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by aevyrie** [aevyrie/bevy_mod_picking#138]
**To agree to this relicense, please read the details in this issue, then leave a comment with the following message:**

`I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.`

If you disagree, please respond with your reasoning (just don't expect us to change course at this point). Anyone who doesn't agree to the relicense will have any contributions that qualify as "copyrightable" removed or re-implemented.

Why: https://github.com/bevyengine/bevy/issues/2373

# What will this look like?

After getting explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright, due to not being a "creative
work", e.g. a typo fix), we will add the following file to our README:

### License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
additional terms or conditions.

We will add LICENSE-{MIT,APACHE} files containing the text of each license. We will also update the license metadata in our Cargo.toml to:

license = "MIT OR Apache-2.0"

**Comment by Ratysz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by obsgolem** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by gavlig** [comment]
I license past and future contributions to bevy_mod_picking under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

(I specified the project name in text, hope that's alright)

**Comment by YoshieraHuang** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mcobzarenco** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by thlorenz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by BrunoWallner** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by RishiKumarRay** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by aevyrie** [comment]
Re-pinging:
@docDock 
@nicbarker 
@Nickan 
@verzuz 
@UnFlimFlammable

**Comment by UnFlimFlammable** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to choose either at their option.

**Comment by verzuz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Nickan** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by olegomon** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
