### ISSUE TITLE
impl `GetTypeRegistration` for `RayCastMesh<PickingRaycastSet>`

### ISSUE THREAD

**Issue by kgv** [aevyrie/bevy_mod_picking#149]
In order to be able to save / load scenes that contain components from the `PickableBundle`.
We need register type: `app.register_type::<RayCastMesh<PickingRaycastSet>>()`. But this requires impl `GetTypeRegistration`.

**Comment by aevyrie** [comment]
This should be resolved in https://github.com/aevyrie/bevy_mod_picking/commit/b66dfd3f859dba2d60d2265cf3064a5e432b2cfe
