### ISSUE TITLE
Do not require render feature group

### ISSUE THREAD

**Issue by Shatur** [aevyrie/bevy_mod_picking#157]
The used `render` feature is a [group](
https://github.com/bevyengine/bevy/blob/a291b5aaedb4affcb31df2e2e63cb0c665ffb24a/Cargo.toml#L35-L43) that contains unneeded stuff, like `bevy_ui` or `bevy_text`. It would be great to require specific bevy components as you did in [`bevy_mod_raycast`](https://github.com/aevyrie/bevy_mod_raycast/blob/5949fc7f021e6900c3d14b4e6f22ef4426489441/Cargo.toml#L14-L17).
 You can read more about in in this issue: https://github.com/bevyengine/bevy/issues/4202 and also see https://github.com/bevyengine/bevy/issues/5753

**Comment by Shatur** [comment]
Will be closed by #137.

**Comment by NiklasEi** [comment]
I think this can be closed?

**Comment by Shatur** [comment]
Yes!
