### ISSUE TITLE
Preserving/overlaying the original material on hover/selection

### ISSUE THREAD

**Issue by philpax** [aevyrie/bevy_mod_picking#166]
Hi there! 

I'm using `bevy_mod_picking` to select entities within my tool; however, I'd like to preserve the existing material when an entity is hovered/selecting, and show a modified version of the material (for now, a coloured overlay over the original material would be sufficient - like selecting a word in text)

My understanding is that the highlight materials are global, which would make this somewhat difficult. Is there a way to do this / are there any plans to make this easier?

I'm working with textured plane meshes, so changing the material results in them losing their visual identity. Any suggestions would be appreciated!

**Comment by aevyrie** [comment]
The plugin stores a handle to the original material, and swaps in a modified version depending on the current hover/selection state. If I'm understanding your request, it sounds like the plugin is already doing what you want (preserving the original material).

Highlighting settings are global per asset type, but can be overridden per-entity.

**Comment by philpax** [comment]
Sorry, I realise that my initial issue was a little unclear! I have a plane with a texture, and when I hover over it, its material is entirely replaced with the highlight (which appears to be black - not sure what's going on there, but probably unrelated):
![image](https://user-images.githubusercontent.com/707827/197589049-5ad4c124-45ca-435c-9de3-c744554198d1.png)
and if I select it, it's dark blue:
![image](https://user-images.githubusercontent.com/707827/197590879-633575c3-0ccf-4b08-b74e-d2927f060dd2.png)

What I'd like is for the highlight material to be a variant of the initial material, so that you can still see it. In this case, I've just recoloured it blue, but I could see other overlays being viable (especially for the other states)
![image](https://user-images.githubusercontent.com/707827/197589669-42284400-0873-44cd-8864-d3cdd8740169.png)
(apologies for the very haphazard edit)

The dream would be to have a outline, like Blender, but this will probably require a shader (perhaps https://github.com/YoshieraHuang/bevy_outline could work for this?)
![image](https://user-images.githubusercontent.com/707827/197590136-0a04e424-d4e0-413e-b97e-2632c0429c35.png)

If highlighting settings can be overridden per-entity, I should be able to generate recoloured variants of my materials and load them in for hover/selected/selected hover (a little wasteful, but totally fine for my application). Is that correct, and if so, how does the override work? I saw #103, but I wasn't sure if replicating that system was still the best way to do it today.

**Comment by aevyrie** [comment]
For your use case, the supplied highlighting system isn't going to work without some elbow grease. I'd recommend you roll your own, it's pretty straightforward. You can use the `Highlight` and `Selection` components to decide what to switch your material to, or use that information to toggle something like bevy_outline.
