### ISSUE TITLE
Retrieving Larger Entity from GLTF Scene w/ Pickable Mesh and Event Bubbling

### ISSUE THREAD

**Issue by InfernoStats** [aevyrie/bevy_mod_picking#167]
I'm trying to despawn an entire entity but using the `make_pickable` function below results in removing singular mesh *faces* of my model. I've even tried grabbing the component of the entity, but the query never returns successful when passing in a single mesh.

```Rust
struct GetAttrInfo(Entity);
impl<E: IsPointerEvent> ForwardedEvent<E> for GetAttrInfo{
    fn from_data(event_data: &PointerEventData<E>) -> Self {
        Self(event_data.target())
    }
}
impl GetAttrInfo{
    fn handle_events(
        mut click_events: EventReader<GetAttrInfo>,
        mut query: Query<(Entity, &mut Attribute), With<Attribute>>,
    ) {
        for event in click_events.iter() {
            if let Ok((_, attr)) = query.get_mut(event.0) {
                println!("Clicked on Entity: {:?}", attr.frozen);
            } else {
                println!("Failed to get entity: {:?}", event.0);
            }
        }
    }
}
```

I've used the following code to make a GLTF Scene pickable:
```Rust
fn make_pickable(
    mut commands: Commands,
    meshes: Query<Entity, (With<Handle<Mesh>>, Without<PickRaycastTarget>)>,
) {
    for entity in meshes.iter() {
        commands
            .entity(entity)
            .insert_bundle(PickableBundle::default())
            .insert(PickRaycastTarget::default());
    }
}
```

and I'm spawning these GLTF scene bundles with:
```Rust
#[derive(Component)]
struct Attribute {
    pub frozen: bool,
}

let object_handle: Handle<Scene> = asset_server.load("object.glb#Scene0");
...
    commands
        .spawn_bundle(SceneBundle {
            transform: transform
                .with_scale(Vec3 {
                    x: 0.0075,
                    y: 0.0075,
                    z: 0.0075,
                })
                .with_rotation(Quat::from_rotation_y(std::f32::consts::PI * 1.5)),
            scene: object_handle.clone(),
            ..default()
        })
        .forward_events::<PointerClick, GetAttrInfo>()
        .insert(Attribute{ frozen: false });
```

Any help would be greatly appreciated! For reference, I am using the current `refactor` branch.

**Comment by InfernoStats** [comment]
After messing around with some queries it looks like the hierarchy is as follows:

-> = is parented by

3235v0 -> 3234v0 -> 3233v0 -> 21v0

3235v0 - Clickable Face
3234v0 - Object - Two faces on the same object resolve to this same ID
3233v0 - Some intermediary entity container
21v0 - The actual object entity created from the initial SceneBundle spawning

**Comment by aevyrie** [comment]
> I'm trying to despawn an entire entity but using the `make_pickable` function below results in removing singular mesh _faces_ of my model. I've even tried grabbing the component of the entity, but the query never returns successful when passing in a single mesh.

When you say "entire entity" do you mean the entity hierarchy? E.g. the topmost entity and all of its children?
If so, this is happening because you are returning the _target_ of the click (the face that was clicked on), instead of the event _listener_ (the top level GLTF scene entity).

You probably want:

```rs
struct GetAttrInfo(Entity);
impl<E: IsPointerEvent> ForwardedEvent<E> for GetAttrInfo{
    fn from_data(event_data: &PointerEventData<E>) -> Self {
        Self(event_data.listener())
    }
}
```

The problem you are describing is exactly why event listeners exist, they propagate events up the entity hierarchy, so you don't need a `get_parents_by_level` function.

See: https://github.com/aevyrie/bevy_mod_picking/blob/298df1428aefda95fb6b90e34cbc91d95376efb3/crates/bevy_picking_core/src/output.rs#L175-L185

**Comment by InfernoStats** [comment]
> When you say "entire entity" do you mean the entity hierarchy?

Yep, I'm new to Bevy and didn't have the proper terminology to reference the top-most parent entity which holds the component.

> You probably want:

You're exactly right! Thank you ❤️

**Comment by aevyrie** [comment]
Glad to hear that was helpful!
