### ISSUE TITLE
Don't deselect entities if they've been just selected by a non-builtin system on a mouse click

### ISSUE THREAD

**Issue by mvlabat** [aevyrie/bevy_mod_picking#187]
Hi! Thank you for your wonderful crate :)

I'm unsure if this is a feature or a help request.
I'm trying to select an entity on an Egui button click. It doesn't work, and if I understand that correctly, the reason is that a click event is emitted at the same frame, which immediately deselects the entity I've just marked with `set_selected(true)`.
If that is correct, is there any way to work around the problem?

Ideally, I'd be happy if there was a way to make `bevy_mod_picking` ignore mouse and/or keyboard input, but without disabling all other systems. It seems to me that tweaking `PickingPluginsState` doesn't make it possible atm.

**Comment by aevyrie** [comment]
This is addressed on the beta branch:

- It adds the concept of "backends" which feed intersections to the picking plugin. It allows us to have a backend for raycasting, egui, etc.
- There is a component called `NoDeselect`. When this component is on an entity, when it is clicked it will not deselect other entities.
- There is a backend for egui, [which assigns all of egui to a single entity](https://github.com/aevyrie/bevy_mod_picking/blob/3f211b0ba7c76a42c4af9d45910ed3b4c3d5bd6d/backends/bevy_picking_egui/src/lib.rs#L47) that has the `NoDeselect` component. This means that when you click on anything in egui, it will not deselect other things.

**Comment by aevyrie** [comment]
This has been released for a while, and can be seen in the egui example.
