### ISSUE TITLE
Plugin interferes with handrolled picking functionality, but only when using left click

### ISSUE THREAD

**Issue by alice-i-cecile** [aevyrie/bevy_mod_picking#188]
Encountered during https://github.com/Leafwing-Studios/Emergence/pull/262

On this branch, my tile picking logic was behaving bizarrely: only Shift + Click was working, while simple click and control click were used directly. Use https://github.com/Leafwing-Studios/Emergence/pull/262/commits/14344f12c9f6444bbe1d1673fe83f88da62b6e5d to test.

I at first thought I had a bizarre input binding / clash bug in `leafwing_input_manager`, that was somehow working previously. However, moving the keybindings to `MouseButton::Right` rather than `MouseButton::Left` fully resolved the issue.

I think that this plugin is subtly messing with the left mouse inputs in very surprising ways? I'd have to dig through.

For now, I think my next step is to drop down into `bevy_mod_raycast`, as I'm not using the more premade functionality exposed by this crate.

**Comment by alice-i-cecile** [comment]
Resolved by swapping to a simpler `bevy_mod_raycast` solution: https://github.com/Leafwing-Studios/Emergence/pull/262/commits/c661fd1bcdb030b5e1c2661a826d53396ae3dc28

**Comment by aevyrie** [comment]
Are you using the beta branch, or crates.io?

If you're on beta, defaults inputs can be disabled, and you can use whatever you want to trigger input eveents.

**Comment by alice-i-cecile** [comment]
Currently on the `crates.io` form :) I wanted to test the old API first to have a better opinions.

**Comment by aevyrie** [comment]
Closing as inputs are now completely decoupled from plugin logic.
