### ISSUE TITLE
Broken touches in a 0.11 version

### ISSUE THREAD

**Issue by silvestrpredko** [aevyrie/bevy_mod_picking#190]
I am starting to use an ```0.11``` version for my mobile game. And saw that If I use a touch screen(simulator or real device). The picking isn't working correctly.

```log
...
[2m2023-03-06T20:02:56.662405Z[0m [32m INFO[0m [2mbevy_mod_picking::focus[0m[2m:[0m Hover Just pressed None
[2m2023-03-06T20:02:56.672014Z[0m [32m INFO[0m [2mbevy_mod_picking::focus[0m[2m:[0m Hover Just pressed None
...
```

As a result tapping on a screen doesn't trigger a click event.

If the version is ```0.10``` everything is working just fine.

<img width="990" alt="image" src="https://user-images.githubusercontent.com/3709476/223218010-56dbef1e-4f5b-4679-8588-b112a4101672.png">

I saw a diff between 0.10 and 0.11 in a ```mesh_selection```and ```mesh_events_system```. I am looking into the code and trying to find a quick fix, but unfortunately, it's not so simple for me to find it quickly.

_Steps to reproduce:_
Just run the example ```events``` on the iOS simulator or on the real device

**Comment by aevyrie** [comment]
Closing this as the input system has been completely rewritten and tested with multitouch.
