### ISSUE TITLE
feature request - Double Click

### ISSUE THREAD

**Issue by dennisorlando** [aevyrie/bevy_mod_picking#201]
Hi, it would be amazing to have a new "DoubleClick" event (or perhaps a "MultipleClick" one), maybe something like this?
- configurable time delay that defaults to 400ms (default time delay for most apps and desktops)
- another configuration that makes it either fire a "doubleclick" while still firing single "click" events or firing "doubleckick" events and blocking single click events that would be generated
- reset delay when moving around, or perhaps only dire this event if the target is the same entity in both cases (as you are already doing with "click")
- maybe as an optional feature?

**Comment by aevyrie** [comment]
This may be difficult to implement without https://github.com/bevyengine/bevy/issues/5984

Because multi clicks happen rapidly, there is a non-insignificant chance that they will be gobbled up between frames.

**Comment by dennisorlando** [comment]
> This may be difficult to implement without [bevyengine/bevy#5984](https://github.com/bevyengine/bevy/issues/5984)
> 
> Because multi clicks happen rapidly, there is a non-insignificant chance that they will be gobbled up between frames.

Do you mean that maybe you get like "Down - Down - Up - Up" instead of "Down - Up (Click) - Down - Up (Click, DoubleClick"?

**Comment by aevyrie** [comment]
Not all users will be running at 60Hz, and it's possible for the application to hitch, causing a buildup of inputs. It won't be an an issue in most cases, but it also means the faster that someone double clicks, the more likely this is to occur.

On an unrelated note, I'm also not certain what the best course of action is for getting the threshold timing. This is user-configurable, and is needed especially for accessibility reasons.

**Comment by aevyrie** [comment]
Marking this as a wontfix for the time being. We can reconsider if we get better support in bevy, or get access to system double click settings.
