### ISSUE TITLE
feature request - target multiple components with OnPointer::<>::target_component_mut

### ISSUE THREAD

**Issue by dennisorlando** [aevyrie/bevy_mod_picking#202]
Hi, I have a component with a Transform and a "Selected" component; I want to move it on Drag only if it's selected, but it's really tedious to do so because I can only access one component at a time with "target_component_mut" and I can't propagate the drag vector to an event because if I used "OnPointer....::send_event() then I wouldn't have access to the event in the send_event() body

I'm currently using run_callback but I don't really like it because it prevents parallelization

BTW: really great project :)

**Comment by dennisorlando** [comment]
EDIT: if I use run_call back then I lose information regarding the specific entity that got the OnPointer event (i.e. that was clicked);

**Comment by aevyrie** [comment]
You can use `run_callback` - all the helper methods, like `target_component_mut` use `run_callback` under the hood. The event data is passed into the system with `In<ListenedEvent<E>>`:

https://github.com/aevyrie/bevy_mod_picking/blob/3dc4c5cb2e18d0794937c885db905aa057a298fb/examples/event_listener.rs#L133-L134

Event data is available for all of these helpers, including `send_event`, which impls `From<ListenedEvent>`:

https://github.com/aevyrie/bevy_mod_picking/blob/3dc4c5cb2e18d0794937c885db905aa057a298fb/examples/event_listener.rs#L149-L153
