### ISSUE TITLE
How to implement "when space is pressed, disable mouse pick"?

### ISSUE THREAD

**Issue by AllenDang** [aevyrie/bevy_mod_picking#206]
I have a system to let use drag-move the camera by press space + mouse left button down + mouse move, in the mean time, I need to disable picking when space is pressed.

Do I need to implement a customized Pointer?

How to implement it?

**Comment by aevyrie** [comment]
While space is pressed, disable picking or maybe just input capture, using the settings: https://docs.rs/bevy_picking_core/0.1.0/bevy_picking_core/struct.PickingPluginsSettings.html
