### ISSUE TITLE
Picking misses plane at specific angles with orthographic projection

### ISSUE THREAD

**Issue by dmlary** [aevyrie/bevy_mod_picking#209]
I'm using a plane centered on the origin to get x/z coords.  I discovered that with an orthographic projection, raycasting will miss the bottom edge of the plane if the camera has some rotation.  Looking straight (or nearly so) down, and the problem goes away.

https://github.com/aevyrie/bevy_mod_picking/assets/857742/3a9802b8-9a34-4812-a9a5-038e7ee83b6f

In this video, the green rectangle is the only Pickable entity.  The plane is correctly picked for most of the screen, but when I mouse over it on the lower portion of the screen, it no longer picks the plane.

If I then rotate the camera to look down, picking works correctly.

This doesn't occur when using perspective projection.

**Comment by aevyrie** [comment]
What picking backend are you using? It looks like the mod_raycast backend?

**Comment by dmlary** [comment]
I believe it is the mod_raycast backend.  I'm using the default features for the crate, and `DefaultPickingPlugins`.

**Comment by dmlary** [comment]
Looking at the implementation of the raycast backend, this does look like it's most likely a bug in `bevy_mod_raycast`.

I'm planning to dig deeper into it tomorrow.  I've confirmed the angle of the camera in reference to the plane does have an impact on where the raycasting stops.  It doesn't matter how large the plane is (working with 10,000x10,000 normally) at a 30 degree angle to the plane, the raycast misses the bottom 1/4th of the screen.  The plane is absolutely present there.

Do you have any suggestions of where to start looking, or any additional data that you'd like to see to help figure this out?  I've started reading the raycast code, but any direction would be appreciated.

**Comment by dmlary** [comment]
Oh, this has something to do with the `depth` of the hit!  I enabled debugging and used the mouse to trace where raycasting stops on the plane.  The only thing that stood out is that once depth should go below `0.0` due to mouse movement, the raycast stops hitting the plane.

https://github.com/aevyrie/bevy_mod_picking/assets/857742/039cf2da-e706-4a3a-b99d-47f220e06cb6

**Comment by dmlary** [comment]
Digging further, I started dumping the results of `Ray3d::from_screenspace` and found that it stops detecting the plane once the `Ray3d.origin` y-value goes negative.  

For a moment I thought maybe the problem was that using `shape::Plane` there is no "back" of the plane.  You can see this when you flip to the other side of the plane and it disappears.  I added a second pickable plane flipped on the x-axis to give the plane a back to pick from if the ray is cast from y < 0.  This did not resolve the problem.

I'm curious now about the calculated `Ray3d.origin()` value.  From an naive perspective, I don't really understand why the Y value for the origin goes negative in this case.  Maybe it's because this is an orthographic projection, not perspective?

https://github.com/aevyrie/bevy_mod_picking/assets/857742/7cbddc86-e510-4af3-846b-60b7617d2e4c

**Comment by aevyrie** [comment]
> it stops detecting the plane once the Ray3d.origin y-value goes negative.

Is this the input ray? My initial suspicion is that the hit is behind the camera (negative depth), which should be ignored, but orthographic view is rendering objects behind the camera.

**Comment by dmlary** [comment]
That's exactly what is going on.  I was just typing up a new issue in `bevy_mod_raycast` for this.

Should `update_raycast()` not prune these hits when doing ortho projection?

**Comment by dmlary** [comment]
### Resolution
Alright, a couple of the problems I had in my code:
* The `Camera` was 5.0 units from the camera focus
* I had increased projection `near` to -100 because I was seeing clipping of tiles at the bottom of the screen as a result of the camera being so close

### Fix / Workaround
Increase the distance of the camera from the focus.  For my case, I increased the distance of the camera to 20, with no change in the on-screen projection.

This will resolve raycast picking issues, and allow a switch to `near: 0`.

**Comment by aevyrie** [comment]
To add to this - setting the near plane negative resulted in objects behind the camera being rendered. Raycasting does not consider objects behind the camera to be hittable. More precisely, it can raycast against these objects, but will ignore them if the hit is behind the camera.

**Comment by dmlary** [comment]
This is resolved by https://github.com/aevyrie/bevy_mod_raycast/pull/84
