### ISSUE TITLE
How to get HitData.position on mouse click?

### ISSUE THREAD

**Issue by GameboyColor32** [aevyrie/bevy_mod_picking#213]
I want to have the world position on mouse click, can this plugin do that? From what I understand it is only for detecting mouse interactions with entities. Thanks in advance

**Comment by GameboyColor32** [comment]
The repo: https://github.com/aevyrie/bevy_mod_raycast fixed my issue

Made by the same author @aevyrie fixed my problem, take a look at the examples.

Thanks !

**Comment by marko-lazic** [comment]
Yeah, I am using mod raycast but it has the have a surface to cast on.

**Comment by aevyrie** [comment]
You can access this data using the HoverMap. Note that the debug overlay shows the hit position and normal.

**Comment by nixpulvis** [comment]
In case anyone else lands here and wants to know how to get the position in an `On::<Pointer<Click>>::target_commands_mut(|click, _| ...)` callback. Here `click` derefs to a [`Click`](https://docs.rs/bevy_mod_picking/latest/bevy_mod_picking/events/struct.Click.html) event with a [`hit`](https://docs.rs/bevy_mod_picking/latest/bevy_mod_picking/events/struct.Click.html#structfield.hit) field, so `click.hit.position` should be what you want.
