### ISSUE TITLE
how to actually do something complex ?

### ISSUE THREAD

**Issue by robbiemu** [aevyrie/bevy_mod_picking#219]
do you know how I can use an EventWriter in run_callback? or what the right strategy would be. My issue is that I have very many entities here, and I can uniquely determine them with values z,x. However, I need to trigger an event to effect the change this click requires. I created a new event:
```rust
pub struct OnClickCover((usize, usize));
```
Because the z,x values must be specified I can't use send_event. So the next likely option is run_callback. This creates a system from your closure, accepts a generic M but it seems that this must be an Res<> value, not an EventWriter.

The "complex" logic requires Res access to resource for my plugin, another for the game/app resource, and a materials resource, so this will not gently fit intosystem

**Comment by robbiemu** [comment]
I'm sorry my rust-analyzer was just being slow for some reason (assuming it wasn't pure human error). Before I was getting an error that IntoSystem not satisfied when I tried to use an EventWriter as my M parameter in run_command. this morning, I'm finding this works just fine:
```rust
          OnPointer::<Click>::run_callback(
            move |In(_): In<ListenedEvent<Click>>,
                  mut cover_events: EventWriter<OnClickCover>|
                  -> Bubble {
              cover_events.send(OnClickCover((z, x)));
              Bubble::Up
            },
          ),
```

at this point I just have to debug why I am getting this panic:
thread 'Compute Task Pool (3)' panicked at 'No camera found associated with pointer Mouse.', /Users/robertotomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_picking_ui-0.1.0/src/lib.rs:67:32

even though I have my camera set up like this:
```rust
            commands.spawn((Camera3dBundle {
    projection: OrthographicProjection {
      scaling_mode: ScalingMode::FixedVertical(8.0),
      ..Default::default()
    }
    .into(),
    transform: Transform::from_xyz(5.0, 6.0, 5.0)
      .looking_at(Vec3::from([-2.0, 0.0, -2.0]), Vec3::Y),
    ..Default::default()
  }, RaycastPickCamera::default()));
  ```

**Comment by aevyrie** [comment]
> No camera found associated with pointer Mouse

This should no longer panic.

> Before I was getting an error that IntoSystem not satisfied 

The `run` callback is just a normal bevy system, it can do anything a bevy system can (note that it was complaining about the `IntoSystem` trait). You can also move your callback into a normal bevy system and call it, though you won't be able to capture any local variables.
