### ISSUE TITLE
Sprite backend does not care if entity is `Pickable`

### ISSUE THREAD

**Issue by bonsairobo** [aevyrie/bevy_mod_picking#223]
This makes it hard to make sprites unpickable (e.g. while they are doing a specific animation).

**Comment by aevyrie** [comment]
I verified this is working as intended in the latest main and should work in 0.15. Backends are no longer required to check `Pickable`. Instead, the core plugin does this filtering and mapping.

Adding a `Pickable::IGNORE` to a sprite made it unpickable.
