### ISSUE TITLE
Bad hover behavior for `bevy_ui` example

### ISSUE THREAD

**Issue by jnhyatt** [aevyrie/bevy_mod_picking#229]
Steps to reproduce:
- Run `bevy_ui` example
- Hover over a button (but not its text), it should change color
- Move the cursor over the text on the same button, the button no longer appears 'hovered'
- At this point, moving the cursor back off the text onto the button still does not trigger 'hovered' appearance

Looking at the logs, it looks like Over events are being generated before Out events. Since both sets of events are bubbling to the button itself, the button receives Out events last and changes to its default state instead of hovered.

This doesn't so much seem like a bug in the crate, just a bug in the example. If there were a way to completely ignore text, this example would work perfectly. Is there a component that can make picks simply ignore certain UI elements? Or is there a better way to fix this behavior?

**Comment by aevyrie** [comment]
This is because the example uses `Over` and `Out` instead of `Enter` and `Exit`, which don't yet exist.
See the distinction here:
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

**Comment by jnhyatt** [comment]
Is there a workaround for this in the meantime? Or do you have plans to add `Enter` and `Leave`? Or is this something I can do?

**Comment by c6p** [comment]
@jnhyatt in the meantime, you can set `FocusPolicy::Pass` on the text. It will send the event twice (once for text, once for the button) though.

**Comment by aevyrie** [comment]
With the refactors to `Pickable` and `PickInteraction`, this is now working correctly. We could take a look at implementing `Enter` and `Leave`, although it will need extra care, as it handles descendants differently from all existing pointer events.
