### ISSUE TITLE
bevy_mod_picking doesn't compile on stable

### ISSUE THREAD

**Issue by bitshifter** [aevyrie/bevy_mod_picking#23]
When running `cargo build --examples` I get the error:

```sh
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Clink-arg=-fuse-ld=lld -Zshare-generics=y --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

This is because `.cargo/config` is in .git and contains options which are only available on nightly.

I think `.cargo/config` shouldn't be committed. Note that `bevy` itself has this file as `.cargo/config_fast_builds` so it won't actually be used until it's been renamed.

**Comment by aevyrie** [comment]
Thanks for reporting this - I added .cargo/config to the .gitignore, but I clearly need to rename it as you suggested.

**Comment by aevyrie** [comment]
Latest PR has fixed this. Thanks @bitshifter!
