### ISSUE TITLE
RaycastSource should use a manual Clone impl rather than a derive

### ISSUE THREAD

**Issue by alice-i-cecile** [aevyrie/bevy_mod_picking#249]
Currently, all of my generic types must also impl Clone, even though they're only used as a `PhantomData`.

This is a well-known footgun in Rust's derive macros unfortunately.

**Comment by aevyrie** [comment]
I think this belongs in `bevy_mod_raycast`?

**Comment by alice-i-cecile** [comment]
Yes it does, sorry!
