### ISSUE TITLE
Asset should be reverted to initial on PickHighlight removal

### ISSUE THREAD

**Issue by barsoosayque** [aevyrie/bevy_mod_picking#250]
This issue arises when I'm trying to remove `bevy_mod_picking` related components from an entity. Maybe it shouldn't track removal of highlight components and this is a more broader issue with removal tracking in the core picking systems, since I had an assumption that removing picking components from the selected entity would be effectively a deselection (which in turn would revert asset to initial to my understanding).

**Comment by aevyrie** [comment]
If you are removing components, that's out of scope of something the plugin can reasonably handle. You will need to halt the highlighting systems, revert the highlight asset to the initial state, then remove the component.
