### ISSUE TITLE
Picking event not working when DebugPickingPlugin disabled

### ISSUE THREAD

**Issue by vav-dev** [aevyrie/bevy_mod_picking#253]
I have some troubles when I want to disable the DebugPickingPlugin.

I have this conf:
```toml
[dependencies.bevy_mod_picking]
version = "0.15"
default-features = false
features = ["backend_raycast", "debug"]
```

I spawn entity with this kind of code: 
```rust
entity_command.with_children(|parent| {
    parent.spawn((
        PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Quad {
                size: Vec2 { x: 1., y: 1. },
                ..default()
            })),
            material: materials.add(Color::NONE.into()),
            transform: Transform {
                translation: Vec3::new(0., 1. + Z_ORDER_2, 0.),
                rotation: Quat::from_rotation_x(
                    -std::f32::consts::FRAC_PI_2,
                ),
                ..default()
            },
            ..default()
        },
        NotShadowCaster,
        CellColorState::Normal,
        CellEventState::None,
        BoardPositionComponent(BoardPosition { i, j }),
        CellComponent,
        AbilityEffectReceived::default(),
        PickableBundle::default(),
        RaycastPickTarget::default(),
        On::<Pointer<Click>>::send_event::<BoardEvent>(),
        On::<Pointer<Over>>::send_event::<BoardEvent>(),
        On::<Pointer<Out>>::send_event::<BoardEvent>(),
    ));
});
```

Everything works fine when I add picking plugin like this:
```rust
app.add_plugins(DefaultPickingPlugins);
```

But when I want to disable the debug gui:
```rust
app.add_plugins(
    DefaultPickingPlugins
        .build()
        .disable::<DebugPickingPlugin>(),
)
```

My systems does not receive the `BoardEvent` anymore.

**Comment by aevyrie** [comment]
The debug plugin simply prints out events and draws debug info on the screen, It shouldn't have any effect on any of the subcrates, as they don't even use this feature. I tested this on the latest version, by updating the eventlistener example with your supplied code to disable the debug plugin. The example continued to work as expected.

We can re-open this issue if you can provide a minimal reproduction, but this issue does not seem to br present in the current version.

**Comment by aevyrie** [comment]
I see the associated commit, this may have been related to a bug that was fixed in the last release.
