### ISSUE TITLE
Consider using debug!() and trace!() instead of info!() for logging

### ISSUE THREAD

**Issue by mattdm** [aevyrie/bevy_mod_picking#259]
While the "info" level is clearly appropriate for bevy_mod_picking as a thing in itself, from the point of view of a higher-level consumer, that seems too escalated. I know it literally says "unofficial" in the title, but I think this guidance [from the Bevy Cheat Book](https://bevy-cheatbook.github.io/features/log.html#levels) makes sense:

>
>  * `error`: something happened that prevents things from working correctly
>  * `warn`: something unusual happened, but things can continue to work
>  * `info`: general informational messages
>  * `debug`: for development, messages about what your code is doing
>  * `trace`: for very verbose debug data, like dumping values

... and correspondingly I think it would be nice if this crate used `debug` for the "normal" messages and `trace` for the "noisy" ones. That leaves "info" available for more high-level messages.

**Comment by mattdm** [comment]
Terminal screenshot to help illustrate why I think this would be useful. With this, the `info!` messages from the `bevy_ui` example stand out even with bevy_mod_picking debug messages also enabled.

![image](https://github.com/aevyrie/bevy_mod_picking/assets/123367/63d0938c-abb8-4879-9e4b-f7e079432d21)

**Comment by aevyrie** [comment]
Really great feedback. I'm sold.

**Comment by aevyrie** [comment]
Fixed by #262
