### ISSUE TITLE
basic keyboard-controlled pointer for `bevy_picking_input`?

### ISSUE THREAD

**Issue by mattdm** [aevyrie/bevy_mod_picking#265]
Would you be interested in a rudimentary default keyboard input, to go next to `mouse` and `touch` (but probably default to `run_keyboard: false`)?

I'm thinking of something like this:

* arrow keys -> pointer move
   * optional modifiers for faster or more precise movement
   * possibly configurable acceleration when holding keys
* space for primary
* backspace for secondary
* not sure what makes sense for a default for middle. shift-space, maybe?
* page up / 
... and if you like my idea for configurable mouse buttons, the keys for this configurable in the same way (in case someone wants WASD, or HJKL for Vim users...). Although I think in this case the movement keys could be duplicated (even if button keys can't because of how that's tracked).

I'm not sure if this should:
* be its own pointer when enabled? (for example, for an accessibility mode?)
* share and control the mouse pointer? (That might be difficult, especially with the buttons.)
* act like the touch pointer, with a transient existence?

Anyway, let me know what you think.

**Comment by aevyrie** [comment]
Not something I'm interested in adding in the plugin itself, I don't want it to become a kitchen sink of random things. This is something that users are probably going to want to implement in their own way, and can do so with the existing API.

**Comment by mattdm** [comment]
Yep, makes sense. When I get around to this I will make a separate crate. Thanks!
