### ISSUE TITLE
Feature request: explain how it works

### ISSUE THREAD

**Issue by stepancheg** [aevyrie/bevy_mod_picking#272]
I have not found in readme of on docs.rs main page an explanation how it works to quickly understand if it is suitable or not. In particular, it is unclear, how expensive it is. E. g. what would be overhead of picking among million items (on screen/total) for example?

**Comment by aevyrie** [comment]
There is a lengthy description of how the plugin works at the top level documentation: https://docs.rs/bevy_mod_picking/latest/bevy_mod_picking/index.html

The expensiveness of picking is completely dependent on the backend you decide to use. If the provided backends are not performant enough, it is incredibly simple to plug your own backend in - this is a core feature of the plugin.
