### ISSUE TITLE
Pick Hidden Components

### ISSUE THREAD

**Issue by dgriffith0** [aevyrie/bevy_mod_picking#275]
I have a use case where I want to click an object that isn't rendered to the screen. For example imagine a greedily meshed cube that was originally a 2x2 set of cubes. I would like to retrieve the entities of the individual hidden cubes and not the rendered mesh.

**Comment by aevyrie** [comment]
In that case you need to set up a backend for this, or use mod_raycast or rapier. If we want to support this OOTB in this plugin, we would need to add this feature to relevant backends, to allow them to hit test against hidden objects.

**Comment by dgriffith0** [comment]
Thanks for the suggestion. Was able to get it working by modifying raycast back end.
