### ISSUE TITLE
Compilation failure: debug_draw not in scope

### ISSUE THREAD

**Issue by hammypants** [aevyrie/bevy_mod_picking#277]
bevy_mod_picking version 0.16.0

When using cargo feature `backend_egui` but not `backend_bevy_ui` the crate fails to compile.

It looks like this is due to `debug_draw` being backed by the feature `backend_bevy_ui` but being added via the `DebugPickingPlugin` under a section conditionally added under the feature `backend_egui` and _not_ `backend_bevy_ui`.

![image](https://github.com/aevyrie/bevy_mod_picking/assets/1095605/a7deca62-54f7-4429-9cac-bf427b54a454)

![image](https://github.com/aevyrie/bevy_mod_picking/assets/1095605/5357e25b-3178-4607-9fc9-cfbe8309faa5)

![image](https://github.com/aevyrie/bevy_mod_picking/assets/1095605/185969fc-0c0f-431e-ad8b-6a4f03b44bb0)

**Comment by aevyrie** [comment]
Thanks for the report, this is now fixed in https://github.com/aevyrie/bevy_mod_picking/commit/8f78621a6c03b73c0b896dc65af8b151d5e01bcc

**Comment by hammypants** [comment]
Thank you for the excellent library!
