### ISSUE TITLE
Drag delay with left mouse button on macOS

### ISSUE THREAD

**Issue by JeanMertz** [aevyrie/bevy_mod_picking#283]
I don't know why this happens, but on my Mac, with macOS 14.1, the `drag_and_drop` example has a small delay between when I start dragging a square, and when the dragging actually happens. If I click on a square with the LMB and immediately start moving the mouse, the square stays in the old place for a fraction of a second, before it snaps to the new cursor position, after which it stays attached without any stutter until I release the LMB.

This delay is not present when using the right mouse button or middle mouse button in the same example.

Initially, I noticed the problem in my own project, but in a much more substantial way (e.g. the target object stays in the original position 3–4 times longer than in the example, before it snaps to the current cursor position). I thought I was doing something wrong, but after seeing the `drag_and_drop` example showing the same behavior (but in a less extreme way, potentially because my project is more complex/has more drag targets/etc.), I have to conclude that it's either a bug in the mod, Bevy, or something specific to my machine. I should note that I also have a camera-drag system that only uses Bevy types, which does not show any delay:

```rust
pub fn camera_drag(
    mut cameras: Query<(&mut Transform, &OrthographicProjection), With<Camera>>,
    buttons: Res<Input<MouseButton>>,
    mut motion: EventReader<MouseMotion>,
) {
    if !buttons.pressed(MouseButton::Right) {
        return;
    }

    for MouseMotion {
        delta: Vec2 { x, y },
    } in motion.read()
    {
        for (mut transform, projection) in cameras.iter_mut() {
            let scale = projection.scale;

            transform.translation.x -= x * scale;
            transform.translation.y += y * scale;
        }
    }
}
```

**Comment by JeanMertz** [comment]
Ah, I just realized my camera drag implementation uses the _right mouse button_, which works correctly, even for this mod. After I switched the camera drag to also use LMB (and disabled this mod, just to be sure), I also observed the delay in that case, so it's unrelated to this mod, but either Bevy, Winit, or my machine that's causing the issue.

Apologies for the confusion.

**Comment by aevyrie** [comment]
This is caused by the magnet app, for future reference.
