### ISSUE TITLE
How to disable multiselect?

### ISSUE THREAD

**Issue by ddorstijn** [aevyrie/bevy_mod_picking#310]
I am sorry if this is a stupid question. But I can't seem to find a way to disable multi select. How can I do this?

**Comment by aevyrie** [comment]
You can either: remove `PointerMultiSelect` from the pointer, for per-pointer control: https://github.com/aevyrie/bevy_mod_picking/blob/893336bf64265ee7d4bec2e1fefc16fb3e96e57a/crates/bevy_picking_selection/src/lib.rs#L79

or, you can disable the default multiselect system, and provide your own that can be toggled: https://github.com/aevyrie/bevy_mod_picking/blob/893336bf64265ee7d4bec2e1fefc16fb3e96e57a/crates/bevy_picking_selection/src/lib.rs#L37
