### ISSUE TITLE
transparency and overlapping problems with sprite picking

### ISSUE THREAD

**Issue by MonforteAdrian** [aevyrie/bevy_mod_picking#324]
I am trying to use the picking on an isometric tilemap, but I am encountering two problems.
The transparent corners of the isometric tile png are also picked. Is there any way I can fix this?
The isometric tiles overlap one another and when you put the cursor on top of one tile, this one is detected until you get out of it, even when you are in another tile in the middle of the proccess. This causes to skip half of the tiles detection.

**Comment by aevyrie** [comment]
The sprite backend is pretty rudimentary. You would need to do one of the following:
- Add an additional check in the backend that looks at the pixel value under the pointer, and compares against some transparency threshold
- Use a picking shader, which should automatically respect trasparency
