### ISSUE TITLE
Click handlers not firing on mesh

### ISSUE THREAD

**Issue by mahulst** [aevyrie/bevy_mod_picking#344]
Issue already resolved, only filing it so others are aware of it if they encounter the same problem.

I added a click handler to a mesh that never fired:
``` 
commands
  .spawn((
      MaterialMesh2dBundle {
          mesh: mesh_handle.clone().into(),
          ..default()
      },
      On::<Pointer<Click>>::run(click_handler),
  ));
``` 

Turns out the mesh created from code and before picking I only needed it to exist while rendering:
```
    Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::RENDER_WORLD,
    )
```
Picking does need it in the MAIN_WORLD though, so it should be 
``` 
    Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::all(),
    )
```

**Comment by aevyrie** [comment]
To add more context, picking doesn't need this, the mod_raycast *backend* for picking does. If you are using a picking shader as the backend, you would not need the mesh to stay loaded on the CPU.

**Comment by mattlennon3** [comment]
Thankyou @mahulst for posting here. I have been losing my mind as to why my click event wasn't firing! 🙏  👏 

I was using `RaycastPickable` as part of my bundle, I am just coming back to this project from a few months prior and bumped versions etc.

I appreciate the answer too Aevyrie, although I'm not 100% clear. I am not sure what I lose by removing the `RaycastPickable`.

Also I was confused how I was supposed to add the `RenderAssetUsages::all()` to my mesh bundle.

e.g:
```rust
// Where does this fit in?
    let mesh = Mesh::new(PrimitiveTopology::TriangleList, RenderAssetUsages::all());

  // This was the previous bundle:
    let bundle = MaterialMesh2dBundle {
        mesh: meshes.add(Circle::new(radius)).into(),
        material: materials.add(ColorMaterial {
            color: colour.into(),
            texture: None,
        }),
        transform: *transform,
        ..default()
    }
```

Not that I need to now I've removed the RaycastPickable!

**Comment by aevyrie** [comment]
> although I'm not 100% clear. I am not sure what I lose by removing the RaycastPickable.

This is documented:

https://docs.rs/bevy_picking_raycast/0.20.0/bevy_picking_raycast/struct.RaycastPickable.html

You likely inherited this from an old version of the plugin, and did not remove it when it became optional.
