### ISSUE TITLE
[Question + Custom Backend] `Drag` doesn't seem to respect camera scaling

### ISSUE THREAD

**Issue by GlennFolker** [aevyrie/bevy_mod_picking#371]
As the title suggests, `Drag`'s `delta` seems off when camera scaling is changed.

When the camera viewport scale is decreased (i.e. zooming in), dragging things become way faster than the cursor:

https://github.com/user-attachments/assets/220e6ee7-619f-49c2-a67d-0babf3bbd336

Normal scaling makes dragging correctly follow the cursor:

https://github.com/user-attachments/assets/e70c3f00-723c-4844-b880-2f3a4b592277

However, I'm not entirely sure if this is on the library or me, because I wrote my own picking backend for Avian (the 3D version exists but not 2D...) in [this repository](https://github.com/GlennFolker/centripetal).
Files of interest:
- [picking.rs](https://github.com/GlennFolker/centripetal/blob/e1acf6a2152ba36579be1485e8835cca6e67874a/src/picking.rs) (the backend).
- [collider.rs#185-195](https://github.com/GlennFolker/centripetal/blob/e1acf6a2152ba36579be1485e8835cca6e67874a/src/editor/widgets/collider.rs#L185-L195) (how I used `Drag::delta`).
- [lib.rs#38](https://github.com/GlennFolker/centripetal/blob/e1acf6a2152ba36579be1485e8835cca6e67874a/src/lib.rs#L38) (how I manipulated the camera scaling).

The recordings above can be reproduced by altering the aforementioned `lib.rs` line 38, and probably increasing the scale of the colliders if you have a hard time trying to drag the vertices at such a large camera scale.

Am I doing anything wrong? I can't make anything out of the documentation, not that I'm much of a math guy anyway... :^)
Any help would be appreciated!

**Comment by darkautism** [comment]
Same probrolem here.
I divided by the camera multiplier to get the correct result.

**Comment by GlennFolker** [comment]
Fixed it too! aevyrie stated in Discord that delta is actually in screenpos, so instead of using the raw delta, I utilized `Camera::viewport_to_world_2d` and everything works perfectly now.
