### ISSUE TITLE
Orthographic Projection Support

### ISSUE THREAD

**Issue by aevyrie** [aevyrie/bevy_mod_picking#4]
This plugin should be agnostic to camera transform. Bevy currently forces the 3d camera bundle to use a perspective projection. May require a PR in bevy to fully button this up.

**Comment by aevyrie** [comment]
As of #26, this might work. The only thing related to the projection matrix is the cursor pick ray construction.

**Comment by tylerkayser** [comment]
I just attempted this using a custom ortho projection and it's still an issue.  I was following this example: https://github.com/jamadazi/bevy-cookbook/blob/master/bevy-cookbook.md#custom-camera-projection

The intersection position reports incorrectly.

**Comment by aevyrie** [comment]
Any chance you could share the code so I can use it as a starting point to debug?

**Comment by tylerkayser** [comment]
> Any chance you could share the code so I can use it as a starting point to debug?

Sure!  Here you go:
https://github.com/tylerkayser/bevy_picking_example

**Comment by aevyrie** [comment]
Thanks! I'll take a look.

**Comment by aevyrie** [comment]
Fixed! Will merge the changes shortly.

![ezgif-1-07dfc7209fb9](https://user-images.githubusercontent.com/2632925/104835097-09855a00-5859-11eb-8280-362249894b96.png)

**Comment by tylerkayser** [comment]
Thanks!
