### ISSUE TITLE
Break ray construction out into its own system allowing user defined rays

### ISSUE THREAD

**Issue by nickbryan** [aevyrie/bevy_mod_picking#43]
It would be awesome to have the ability for a user to be able to define custom rays that is consumed by the picking system. 

I am not sure if it would be possible to allow a user to either cast a ray from screen coordinates (in which case the mouse position is just another screen coordinate) or cast from a world coordinate. I don't know if these cases would need to be handled separately (I am new to the world of ray casting).

My initial thought was just to extract the [cursor position code](https://github.com/aevyrie/bevy_mod_picking/blob/master/src/lib.rs#L364) into some user-defined position but then I wasn't sure if the user would have to specify the position from their system in one frame and not be able to get the result until the next frame (some sort of queue?).

I would be happy to try and help out if you need an extra pair of hands but would need to ask some questions or be guided on what you are currently thinking when it comes to approaching this.

Great work so far by the way!

P.S I am Joonipah on the Discord channel.

**Comment by aevyrie** [comment]
Thanks for writing this up @nickbryan!

As this is already a sort of work in progress (see PR #42) I think the biggest thing I need help with right now is understanding the user-facing plugin API for this set of features.

For example, 

1. What is your use case?
2. How would you expect to give this information to the plugin? (E.g. a Resource?)

> but then I wasn't sure if the user would have to specify the position from their system in one frame and not be able to get the result until the next frame (some sort of queue?).

I think bevy stages might be able to help here, e.g. the user could define a system that updates the position, but it runs before the picking system runs. I'm not sure how this should be implemented - can we specify in the plugin that all picking happens in a later stage, or do we force the user to define their custom picking system in an earlier stage? What are the tradeoffs?

**Comment by nickbryan** [comment]
I think what you are doing with #42 is definitely heading in the right direction. Using a `PickingCamera` component to mark the camera removes the complexity of trying to store the camera entity for the user when the camera is defined in a different system to the picking setup. I had a similar idea around the `PickingGroup` stuff you have started too and I think this could be developed further to encapsulate some of the ideas for defining picking coordinates.

To answer your questions:

1. Currently I have an RTS style camera that is sitting at an isometric view in my world. I would like to be able to allow the user to rotate the camera (Arc Ball) around its focal point. The only way I can think of doing this at the moment is to cast a ray from the centre of the screen and then rotate around the point of intersection with the first mesh. I have this working at the moment by using the current implementation you have in this library but because it is tracking the mouse, the screen jumps to the mouse position instead of staying where it is but rotating around its centre. So this is what lead me onto needing to be able to cast from the centre of the screen rather than mouse position.

Another idea (not sure if this how it would be done in a real game) might be that if you were building a stealth game and you needed to know if an enemy was looking at you, you might cast a ray from the enemies head (in world coordinates) to see if it intersects with the player mesh. This will allow you to be able to see if the player was seen by an enemy or not.

2. I have been thinking over the API for this for a while and it's a tough one to get right. Allowing this to all happen in one frame is where the complexities come in for me. I think I would expect to be able to do something like the following:
```rust
...
.add_startup_system(setup.system())
.add_system_to_stage(bevy_mod_picking::PICK_DEFINITION_STAGE, define_ray_system.system())
.add_system_to_stage(bevy_mod_picking::PICK_COMSUMPTION_STAGE, consume_ray_system.system());

struct MyPickGroup(bevy_mod_picking::PickingGroup);

fn setup(...) {
    // PickingGroups defines the id of the group
    let pick_group: bevy_mod_picking::PickingGroup = bevy_mod_picking::PickingGroups::new();

    commands
        .spawn(Camera3dComponents {
            transform: Transform::new(Mat4::face_toward(
                Vec3::new(-3.0, 5.0, 8.0),
                Vec3::new(0.0, 0.0, 0.0),
                Vec3::new(0.0, 1.0, 0.0),
            )),
            ..Default::default()
        })
        .with(bevy_mod_picking::PickingCamera::new(pick_group))
        .spawn(PbrComponents {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 1.0 })),
            material: materials.add(Color::rgb(1.0, 1.0, 1.0).into()),
            transform: Transform::from_translation(Vec3::new(0.0, 1.0, 0.0)),
            ..Default::default()
        })
        .with(bevy_mod_picking::PickableMesh::new(pick_group));

    commands.insert_resource(MyPickGroup(pick_group));
}

fn define_ray_system(mut pick_groups: ResMut<bevy_mod_picking::PickGroups>, my_pick_group: Res<MyPickGroup>) {
    pick_groups.add_ray_to_group(my_pick_group.0, "my_custom_ray_cast", bevy_mod_picking::RayDefinition::screen_space(Vec32:new(10, 10));
}

fn consume_ray_system(pick_state: Res<bevy_mod_picking::PickState<MyPickingGroup>>) {
    println!("{:?}", pick_state.ray("my_custom_ray_cast").top());
    // pick_state.list() gives all regardless of ray name in this group
    // pick_state.top() gives top regardless of ray name in this group
    // pick_state.ray("name").list() gives all for this name in this group
    // pick_state.ray("name").top() gives top for this name in this group
}
``` 

I appreciate that this might not be the ideal API for this at the moment but I am struggling to come up with an alternative with my current Rust knowledge. I am not sure if the string named rays are the correct way to go.

You could have an option to create a pick group with pre defined rays and then have something like:
```rust
    bevy_mod_picking::PickingGroups::new()
        .with_ray("mouse_position", bevy_mod_picking::RayDefinition::cursor())
        .with_ray("custom_ray", bevy_mod_picking::RayDefinition::custom(...));
```

**Comment by aevyrie** [comment]
Love the detail here, thank you. I'm calling it quits for the day, and I'll have to read through your post in more detail tomorrow. In the meantime, I have the PR in a workable state that might fit your needs. The only API changes are:

1. The new() function for PickableMesh component requires a group be specified. Most users probably don't need this, so I've created a default() fn that puts everything in group 0: `.with(PickableMesh::default())`
2. Basically any entity with a Transform can be the ray source if all you need is a ray shooting out from this source (your use case). There is also an option to supply a position in ndc (screen space) or to just use the cursor (default). Both of these latter two options require the picking source to be a camera because they require a projection matrix.

To use the new ray construction with the mouse cursor, just add this component to your camera: `.with(PickingSource::default());`.

If you want to use the "ray shooting out of the center" method, it will look like `.with(PickingSource::new(PickingGroup::Default(), PickingMethod::Center));`

I'm pretty happy with this solution at first blush, it seems really simple for the user and the implementation. I'll take a closer look at your post tomorrow!

**Comment by nickbryan** [comment]
Haha, that's crazy that I am just starting my day and you are ending yours. I will have a look over this, it sounds awesome! Looks like you may have a much cleaner API than I was thinking from looking at your reply, kudos!

**Comment by aevyrie** [comment]
We had quite a bit of discussion in PR #42. I closed the multi window/camera issue, however I wanted to leave this open to see if there is anything else you'd like to change before closing. If there are additions you want, we can create another issue. 😄

**Comment by nickbryan** [comment]
Hey, I had a look over your changes this morning and it's looking really nice! Good job! 🥳 

In regards to your question around names yesterday, I wonder if `PickingMethod::Transform` is less ambigious than `PickingMethod::Center` if it runs on any `Transform`.

Apart from that I am happy for this to be closed 😄 

Thankyou for your patience and for all the work. It's been a pleasure dealing with you!

**Comment by aevyrie** [comment]
Lovely. I like the `::Transform` suggestion, I particularly like that it implies the need for a bevy Transform to function.

> Thankyou for your patience and for all the work. It's been a pleasure dealing with you!

Likewise!
