### ISSUE TITLE
Dealing with UI elements

### ISSUE THREAD

**Issue by guimcaballero** [aevyrie/bevy_mod_picking#51]
Right now if the mouse is over a UI element, like a button, the plugin ignores it completely and still returns picks as if the element wasn't there.

I don't know if it's something that should be dealt with in the plugin, because a user might need picking to work under a UI element. What are your thoughts on this?

I think the best solution would be to provide an option to enable/disable this behavior. Maybe we could create a `PickingBlocker` component that can be added to a UI element to disable picking when on top of it.

**Comment by aevyrie** [comment]
To make sure I understand, you are looking to occlude pickable meshes with UI elements?

Alternatively, is there a way the user could easily disable the plugin while interacting with the UI? E.g. during a UI mouseover event, disable picking.

**Comment by guimcaballero** [comment]
> To make sure I understand, you are looking to occlude pickable meshes with UI elements?

Correct. But yeah, I ended up doing the simpler thing of disabling my picking systems while something is being hovered.

For future reference, this is what I did:

```rust
#[derive(Default)]
pub struct HoveringUI(pub bool);

struct PickingBlocker;
fn block_picking_under_blockers(
    mut hovering_ui: ResMut<HoveringUI>,
    mut interaction_query: Query<(&Button, &Interaction, &PickingBlocker)>,
) {
    let mut some_is_hovered = false;
    for (_button, interaction, _) in &mut interaction_query.iter() {
        match *interaction {
            Interaction::Clicked | Interaction::Hovered => {
                some_is_hovered = true;
            }
            Interaction::None => {}
        }
    }
    hovering_ui.0 = some_is_hovered;
}
```

Basically I created `HoveringUI`, which is a resource that keeps a flag for if any UI is being hovered, and I added the `PickingBlocker` component to the buttons which I want to act as blockers.

Then on my selection systems I added the following at the top of the function:

```rust
fn some_select_system(
    pick_state: Res<PickState>,
    hovering_ui: Res<HoveringUI>,
    ... Other queries and resources
) {
    if hovering_ui.0 {
        return;
    }

    ... System code here
}
```

What I wanted was to skip the early return in the systems that deal with picking, and instead change the plugin so it doesn't return picks when the mouse is over a UI item. Then I realized I just have a couple systems, so I went ahead and implemented it this way :).

Do you think it would be worth to add the first snippet of code into the Plugin? I feel like it's not really related to picking, so it might be best to just link to this issue in the Readme and let everyone implement it however they see fit.

**Comment by aevyrie** [comment]
> Do you think it would be worth to add the first snippet of code into the Plugin? I feel like it's not really related to picking, so it might be best to just link to this issue in the Readme and let everyone implement it however they see fit.

I'd propose that the best option would be to add an enable/disable state flag in the top-level PickState resource, which will prevent picking systems from running while disabled. In your example, the plugin is still running in the background, you're just ignoring the output. This means that you will still be paying the performance penalty for picking when in the UI; disabling picking from within the plugin itself will solve this.

As for adding the code that disables picking while hovering UI elements, I'd like to leave that up to the user for now - we can provide an example in the plugin examples. We can always add it down the road if it turns out to make sense.

**Comment by guimcaballero** [comment]
Oh, that's a good idea! I'm opening a PR now with a first implementation of this.

**Comment by aevyrie** [comment]
Merged! 😄 
Let's see if this works well for your UI case.

**Comment by guimcaballero** [comment]
Yup, works great!

Here's how it looks now, for anyone else interested: 

```rust
struct PickingBlocker;
fn block_picking_under_blockers(
    mut pick_state: ResMut<PickState>,
    mut interaction_query: Query<(&Button, &Interaction, &PickingBlocker)>,
) {
    let mut some_is_hovered = false;
    for (_, interaction, _) in &mut interaction_query.iter() {
        match *interaction {
            Interaction::Clicked | Interaction::Hovered => {
                some_is_hovered = true;
            }
            Interaction::None => {}
        }
    }
    pick_state.enabled = !some_is_hovered;
}
```

With nothing special added in the selection systems.

Much cleaner!

**Comment by aevyrie** [comment]
It sounds like this is working well, I'm going to close this. Let me know if you think there is room for improvement in this area.
