### ISSUE TITLE
Suggestion: rename `PickingSource` to `PickSource` in docs

### ISSUE THREAD

**Issue by nicbarker** [aevyrie/bevy_mod_picking#56]
Just got this plugin working - great job 🙂

Seems like `PickingSource` has been renamed to `PickSource`, but the docs and error messages all reference `PickingSource`.

If this is the case, I can make a PR to rename them.

![Screen Shot 2020-10-24 at 1 19 07 PM](https://user-images.githubusercontent.com/2264338/97063323-8b1f7000-15fb-11eb-862c-90fa41dc905e.png)
![Screen Shot 2020-10-24 at 1 19 21 PM](https://user-images.githubusercontent.com/2264338/97063325-8ce93380-15fb-11eb-819c-e74ddb7166ce.png)

**Comment by aevyrie** [comment]
Great catch! 😄 
A lot of stuff is changing or about to change (contingent on my availability), so it's always nice to get some fresh eyes on the docs.

I'd appreciate the PR if you have the time to spend on it!

**Comment by nicbarker** [comment]
Nice, will do 👍
