### ISSUE TITLE
Mouse picking is not updated when mouse is not moved and object is deleted

### ISSUE THREAD

**Issue by Nickan** [aevyrie/bevy_mod_picking#64]
Is there a way not to depend on the cursor_events.latest() when updating the picking on line 263 on lib.rs?

I am thinking of adding a field in PickState the previous_mouse_pos and use it when cursor is not moved, but I would like to know if that's the possible solution, thanks.

Sample code is here: https://github.com/Nickan/bevytest/blob/ad375b83351cd6d698c316ff7d00e82db3f7a824/src/bevy_mod_picking_test.rs

**Comment by aevyrie** [comment]
Hi @Nickan, I'm not sure I follow. Is this a bug you found (title)?

**Comment by Nickan** [comment]
I don't really think it is a bug, but a feature request, sorry for being vague, I will MR later what I want to happen. 

Basically, I want to get the top pick, regardless if the cursor is moving or not.

**Comment by aevyrie** [comment]
Yeah, if you can demonstrate the current behavior and the behavior you are looking for, that will really help me understand. Thanks!

**Comment by aevyrie** [comment]
Closing with merge of #68
