### ISSUE TITLE
Noticable stutter on first hover over a HighlightablePickMesh. 

### ISSUE THREAD

**Issue by kumorig** [aevyrie/bevy_mod_picking#86]
There is a noticeable lag on the first mouse-over a mesh when using `HighlightablePickMesh`.
For example:

https://user-images.githubusercontent.com/5523938/103166939-4b2e7080-486a-11eb-948a-869f551b33c5.mp4

I also have the lag on the example code `3d_scene`.

`cargo run --example 3d_scene --release --features="example_deps"` 

https://user-images.githubusercontent.com/5523938/103166968-8af55800-486a-11eb-97bd-7161a075a2f7.mp4

Above, I'm talking about the small freeze at the ~2.5s mark - it's of course much more noticeable when camera or objects are moving.

I'm using:

* Windows 10 build 1909
* rust 1.51.0-nightly (also tried using stable1.47.0 with same result)
* intel i7-4790K CPU @ 4.00GHz
* NVIDIA GeForce GTX 970

I have also experienced this on another windows-machine with poorer specs but with the same stutter, so I don't believe it's an issue with my machine.

Since it only happens once, I think it is a pretty minor issue, but I'd love if there was a way to "trigger the lag" perhaps during a loading screen,  instead of when the user first interacts with the meshes.

**Comment by aevyrie** [comment]
I'm able to replicate this.

Through process of elimination, it seems that the debug picking plugin is the culprit. While I don't see the debug cursor in your first video (might just be small?) can you check to see if it's in use?

```rust
// App::build() blah blah
.add_plugin(DebugPickingPlugin)
```

**Comment by kumorig** [comment]
Yup, you are correct. I didn't even notice. Sorry for wasting your time!
