### ISSUE TITLE
Provide transform/function to get coordinates in world space

### ISSUE THREAD

**Issue by aevyrie** [aevyrie/bevy_mod_picking#9]
Coordinates are currently reported in ndc space. Use the associated camera transform to convert to world space, evaluating lazily.

**Comment by aevyrie** [comment]
PR #14 implements a function to translate from ndc to world space. To resolve this issue, there should be a function that uses the camera associated with the current PickableMesh to supply the transforms into this function automatically.

**Comment by guimcaballero** [comment]
Another thing to note, the current implementation from #14 considers that the ndc coordinates are correct, so due to #5 world space coords might be wrong for objects such as large planes, where the depth from the first vertex is far away from where the intersection is.

**Comment by aevyrie** [comment]
As of #26 default for everything is world space, closing.
