### ISSUE TITLE
Enable/disable picking when mouse enters/leaves the window

### ISSUE THREAD

**Issue by aevyrie** [aevyrie/bevy_mod_picking#94]
Use the `CursorEntered` and `CursorLeft` events to enable and disable mouse picking.

**Comment by YoshieraHuang** [comment]
This is a good idea. Further, a user-defined enable / disable zone may be useful to solve the deselection problem like #134.

**Comment by aevyrie** [comment]
This isn't desired anymore now that the plugin supports more than just mouse input. Users can implement this with the picking settings if they desire.
