### ISSUE TITLE
Add ClickEvent?

### ISSUE THREAD

**Issue by VRichardJP** [aevyrie/bevy_mod_picking#99]
Hi,

First thank you a lot for this great package!

I want to be able to retrieve the world coordinates on the plane y=0  when the user clicks on the screen. I have created a (big) plane on y=0, made it invisible and pickable. With this setup I can get the coordinates I am looking for when the user selects the plane. However, because the same object cannot be selected twice, I always need to deselect the plane manually. Like this:

```
fn mouse_event_debug(
    mut events: EventReader<PickingEvent>,
    mut query: Query<&mut Selection>,
) {
    for event in events.iter() {
        println!("This event happened! {:?}", event);
        if let PickingEvent::Selection(selection) = event {
            if let SelectionEvent::JustSelected(entity) = selection {
                let mut selection = query.get_mut(*entity).unwrap();
                println!("Deselect {:?}!", entity);
                selection.set_selected(false);
            }
        }
    }
}
```

Wouldn't it make more sense to have a ClickEvent instead for this kind of situation? and to be able to have objects that can be clicked but not necessarily selected?

**Comment by aevyrie** [comment]
Yes, I think that would make sense.

**Comment by aevyrie** [comment]
Implemented here: https://github.com/aevyrie/bevy_mod_picking/commit/b4f74a1bdd52719d9e2849802875b5853fd9b8de

Let me know if you have any feedback!
